image:
  file: .gitpod.Dockerfile

ports:
  - port: 8080
    onOpen: open-preview

tasks:
  # manage is a script at .gitpod.yml
  - init: pipenv install && pipenv run manage syncdb --noinput
    command: pipenv run manage runserver 0.0.0.0:8080
    #'cd dojopuzzles && pipenv run python manage.py test && pipenv run python manage.py syncdb --noinput && pipenv run python manage.py runserver'
    # pipenv shell
    # alias manage='python /workspace/dojopuzzles/dojopuzzles/manage.py'

vscode:
  extensions:
    - almenon.arepl@1.0.20:Uu7lIOwyLgmNWpTwCl/iqQ==
    - littlefoxteam.vscode-python-test-adapter@0.3.16:tZ/6xOSSdKUaq6JCUVkD+A==
    - vscode.json-language-features@1.48.0:DuWypSrTW8Q9+ndOejK6kA==