image:
  file: Dockerfile

ports:
- port: 8080
  onOpen: open-preview
  
tasks:
  - init:
        # pip install -r requirements.txt &&
        # cp .env.example .env &&
        # sed -i 's/ALLOWED_HOSTS.*/ALLOWED_HOSTS=\*/' .env &&
        echo "ALLOWED_HOSTS = ['*']" > .env

  - command: >
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8080