image:
  file: .gitpod.Dockerfile

tasks:
  - init: 'pipenv install -r requirements'
    command: 'cd dojopuzzles && python manage.py runserver'

vscode:
  extensions:
    - almenon.arepl@1.0.20:Uu7lIOwyLgmNWpTwCl/iqQ==
    - littlefoxteam.vscode-python-test-adapter@0.3.16:tZ/6xOSSdKUaq6JCUVkD+A==
    - vscode.json-language-features@1.48.0:DuWypSrTW8Q9+ndOejK6kA==